config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :costs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :users
  get '/categories/:category_id/costs/:id/update', to:'costs#update_cost', as: "update_cost"
  #get '/app/assets/images/bg.jpg'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'home', to:'categories#splash', as: 'categories/splash'
  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :costs, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }
  validates :icon, presence: true, length: { minimum: 1, maximum: 3 }

  def transaction_sum
    return Cost.includes(:category).where(category_id: id).sum(:amount) unless Category.all.nil? || Cost.all.nil?

    0
  end
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :costs
  has_many :categories
  validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    if current_user.nil?
      @categories = []
      render('splash')

    else
      @categories = Category.includes(:user).where(user_id: current_user.id)
      @user = current_user
    end
  end

  # GET /categories/1 or /categories/1.json
  def show
    @costs = Cost.includes(:category).where(category_id: @category.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to '/', notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to '/', notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: %i[show edit destroy]

  # GET /costs or /costs.json
  def index
    @category = Category.find(params[:category_id])
    @costs = Cost.includes(:category).where(category_id: @category.id).order(created_at: :desc)
  end

  # GET /costs/1 or /costs/1.json
  def show
    @category = Category.find(params[:category_id])
    @cost = Cost.find(params[:id])
  end

  # GET /costs/new
  def new
    @cost = Cost.new
    @category = Category.find(params[:category_id])
  end

  # GET /costs/1/edit
  def edit; end

  # POST /costs or /costs.json
  def create
    @cost = Cost.new(cost_params)
    @cost.user_id = current_user.id
    @cost.category_id = params[:category_id]

    respond_to do |format|
      if @cost.save
        format.html { redirect_to category_costs_path(params[:category_id]), notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1 or /costs/1.json
  def update
    @cost = Cost.find(params[:id])

    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to category_costs_path(params[:category_id]), notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_cost
    @cost = Cost.find(params[:id])
  end

  # DELETE /costs/1 or /costs/1.json
  def destroy
    @cost = Cost.find(params[:id])
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to category_costs_path(params[:category_id]), notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cost
    @cost = Cost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cost_params
    params.require(:cost).permit(:name, :amount, :user_id, :category_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id] == 'sign_out'
      sign_out
      redirect_to root_path
    else
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category-card w-full mb-5 border rounded-lg p-1">
  <div class="flex p-3 justify-between">

  <div class="icon border text-6xl mx-2 p-3">
    <%= category.icon %>
  </div>

  <div class="flex border-b justify-between w-full p-2">
  <p class="my-3 text-white font-bold text-2xl">
    <%= link_to "#{category.name}", category_costs_path(category) %>
  </p>

  <p class="my-3 text-white font-bold text-2xl">
    $<%= category.transaction_sum %>
  </p>
  </div>
  </div>
  <div class="flex w-full justify-end mb-2 pr-5">
  <% if action_name != "show" %>
    <%#<%= link_to "Show this category", category, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit', edit_category_path(category), class: "border px-4 pt-2 text-white text-lg hover:bg-white hover:text-gray-600 rounded-lg" %>
    <%#<%= link_to 'Show category', category_costs_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-6">
      <%= button_to 'Delete', category_path(category), method: :delete, class: "border p-2 text-white text-lg hover:bg-white hover:text-gray-600 rounded-lg" %>
    </div>
    <hr class="mt-6">
  <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :name, placeholder: "name", class: "rounded-lg w-full py-4 my-2 text-2xl bg-black/[.20] text-white" %>
  </div>

  <div class="my-5 text-white">
    <%= form.text_field :icon, placeholder: "icon (pick an emoji, E.g. 🍦)", class: "rounded-lg w-full py-4 my-1 text-2xl bg-black/[.20] text-white" %>
  </div>

  <div class="w-full flex justify-center">
    <%= form.submit class: "my-2 text-gray-600 bg-white border hover:bg-transparent hover:border hover:text-white text-2xl p-4 rounded-lg mx-auto" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<%= link_to "/" do %>
  <%= image_tag "arrow.png", class:"invert rotate-180", size:"40", alt: "logo" %>
<% end %>
<h2 class="text-white text-4xl text-center">Editing category</h2>
</div>

  <%= render "form", category: @category %>

  <%#<%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%#<%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<h2 class="text-white text-4xl text-center">Categories</h2>
<div class="actions border p-2 text-white text-lg hover:bg-white hover:text-gray-600 rounded-lg">
    <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
  </div>
</div>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div id="categories" class="w-full">
    <%= render @categories %>
  </div>
  <div class="w-full container flex justify-center">
  <%= link_to 'Add new category', new_category_path, class: "my-2 text-gray-600 bg-white border hover:bg-transparent hover:border hover:text-white text-2xl p-4 rounded-lg mx-auto" %>
  </div>
</div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<%= link_to "/" do %>
  <%= image_tag "arrow.png", class:"invert rotate-180", size:"40", alt: "logo" %>
<% end %>
<h2 class="text-white text-4xl text-center">New category</h2>
</div>

  <%= render "form", category: @category %>

  <%#<%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to 'Edit this category', edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this category', category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/categories/splash.html.erb
<div class="mx-auto w-11/12 container flex-col h-full">
<div class="h-3/5 flex justify-center items-center">
<h1 class="font-bold font-['Ubuntu'] text-8xl w-full mx-auto text-center text-white">Penni</h1>
</div>
<div class="container flex-col w-full h-28">
<div class="w-full my-2 text-gray-600 bg-white border hover:bg-transparent hover:border hover:text-white text-2xl font-bold rounded-lg">
  <%= button_to "Log in", new_user_session_path, class: "rounded-lg w-full h-full p-8 hover:border-white" %>
  </div>
  <div class="w-full border text-white hover:bg-white hover:text-gray-600 text-2xl font-bold rounded-lg">
  <%= button_to "Sign up", "/users/sign_up/", method: :get, class: "rounded-lg w-full h-full p-8 border-white hover:bg-white" %>
</div>
</div>
</div>

app/views/costs/_cost.html.erb
<div id="<%= dom_id cost %>" class="cost-card border rounded-lg flex mb-5">
  <div class="flex-col container ml-3">
  <p class="my-5 text-white font-bold text-5xl border-b w-fit pb-3">
    <%= cost.name %>
  </p>
  <p class="my-5 text-white font-bold text-3xl">
    $<%= cost.amount %>
  </p>
  </div>
   
  <div class="flex-col p-3 mt-2">
      <%= button_to "Delete", category_cost_path(category_id: @category.id, id: cost.id), method: :delete, class: "border p-2 text-white text-lg hover:bg-white hover:text-gray-600 rounded-lg mb-5" %>
      <%= link_to 'Edit', update_cost_path(category_id: @category.id, id: cost.id), class: "border p-2 px-5 text-white text-lg hover:bg-white hover:text-gray-600 rounded-lg" %>
    </div>
</div>

app/views/costs/_form.html.erb
<%= form_with(url: category_costs_url, model: cost, class: "contents") do |form| %>
  <% if cost.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
        <% cost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :name, placeholder: "name", class: "bg-black/[.20] text-white rounded-lg w-full py-4 my-1 text-2xl" %>
  </div>

  <div class="my-5">
    <%= form.text_field :amount, placeholder: "amount", class: "bg-black/[.20] text-white rounded-lg w-full py-4 my-1 text-2xl" %>
  </div>

  <div class="w-full container flex justify-center mt-10">
    <%= form.submit "Add expense", class: "my-2 text-gray-600 bg-white border hover:bg-transparent hover:border hover:text-white text-2xl p-4 rounded-lg mx-auto" %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<div class="mx-auto w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<%= link_to category_costs_path(params[:category_id]) do %>
  <%= image_tag "arrow.png", class:"invert rotate-180", size:"40", alt: "logo" %>
<% end %>
<h2 class="text-white text-4xl text-center">New expense</h2>
</div>
  <%= render "form", cost: @cost %>

  <%#<%= link_to "Show this cost", @cost, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/costs/index.html.erb
<div class="w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<%= link_to "/" do %>
  <%= image_tag "arrow.png", class:"invert rotate-180", size:"40", alt: "logo" %>
<% end %>
<h2 class="text-white text-4xl text-center"><%= @category.name %> expenses</h2>
</div>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="text-4xl text-white text-center mb-5 font-bold">
  Total: $<%= @category.transaction_sum %>
  </div>
  <% if @costs.count == 0 %>
  <p class="text-2xl text-white text-center">There are no transactions under this category, add some!</p>
  <% end %>
  <div id="costs" class="min-w-full">
    <%= render @costs %>
  </div>
  <div class="w-full container flex justify-center mt-10">
  <%= link_to 'Add new expense', new_category_cost_path, class: "my-2 text-gray-600 bg-white border hover:bg-transparent hover:border hover:text-white text-2xl p-4 rounded-lg mx-auto" %>
  </div>
</div>

app/views/costs/new.html.erb
<div class="mx-auto w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<%= link_to category_costs_path(params[:category_id]) do %>
  <%= image_tag "arrow.png", class:"invert rotate-180", size:"40", alt: "logo" %>
<% end %>
<h2 class="text-white text-4xl text-center">New expense to <%= @category.name %></h2>
</div>
  <%= render "form", cost: @cost %>
</div>

app/views/costs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @cost %>

    <%= link_to 'Edit this cost', editar_cost_path(@cost), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/costs/update_cost.html.erb
<div class="mx-auto w-full">
<div class="border-b container py-4 w-full mb-5 mt-3 flex justify-between">
<%= link_to category_costs_path(params[:category_id]) do %>
  <%= image_tag "arrow.png", class:"invert rotate-180", size:"40", alt: "logo" %>
<% end %>
<h2 class="text-white text-4xl text-center">Editing expense</h2>
</div>
<%= form_with(model: @cost, url: category_cost_path, method: "patch", class: "contents") do |form| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>
        <strong>This is an update form</strong>
      <ul>
        <% cost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :name, placeholder: "name", class: "bg-black/[.20] text-white rounded-lg w-full py-4 my-1 text-2xl" %>
  </div>

   <div class="my-5">
    <%= form.text_field :amount, placeholder: "amount", class: "bg-black/[.20] text-white rounded-lg w-full py-4 my-1 text-2xl" %>
  </div>

    <div class="w-full container flex justify-center mt-10">
    <%= form.submit "Update expense", class: "my-2 text-gray-600 bg-white border hover:bg-transparent hover:border hover:text-white text-2xl p-4 rounded-lg mx-auto" %>
  </div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Penni</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="lg:max-w-[33%] md:max-w-[50%] lg:mx-auto md:mx-auto bg-slate-700 h-screen"> 
    <main class="container mx-auto px-4 flex h-full blurry-bg bg-gray-300 lg:bg-slate-700 bg-cover w-full bg-repeat-y">
      <%= yield %>
    </main>
  </body>
</html>